###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mariadb:
      image: mariadb:10.4
      container_name: docker-template-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=admin
        - MYSQL_DATABASE=admin
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=admin
      ports:
        - "8203:3306"
    
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      links:
        - mariadb
      ports:
        - 8204:80
      environment:
        - PMA_ARBITRARY=1

    webserver:
      image: nginx:alpine
      container_name: docker-template-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
      - "8200:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: docker-template-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

